import { Connection, PublicKey, Transaction } from 'https://esm.sh/@solana/web3.js@1.98.4?bundle';
import { getAssociatedTokenAddress, createAssociatedTokenAccountInstruction } from 'https://esm.sh/@solana/spl-token@0.4.14?bundle';

const cfg=window.RALYA_CONFIG;
const connection=new Connection(cfg.rpcEndpoint,'confirmed');
const $=id=>document.getElementById(id);
let provider=null,owner=null;
function getProvider(){return window.trustwallet?.solana||window.phantom?.solana||window.solflare||window.solana||null}
function log(msg){const el=$('preTreasuryLog');if(el)el.textContent=`${new Date().toLocaleTimeString()}  ${msg}\n${el.textContent}`.slice(0,5000)}
async function connect(){provider=getProvider();if(!provider?.connect)throw new Error('No Solana wallet detected. Open this private owner page in Trust Wallet, Phantom, or Solflare and try again.');const r=await provider.connect();owner=new PublicKey(r?.publicKey||provider.publicKey);if(cfg.ownerWallet&&owner.toBase58()!==cfg.ownerWallet)throw new Error('Connected wallet is not the configured RALYA owner wallet.');return owner}
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function waitForSignatureConfirmation(signature,lastValidBlockHeight,timeoutMs=75000){const started=Date.now();let polls=0;while(Date.now()-started<timeoutMs){const statuses=await connection.getSignatureStatuses([signature],{searchTransactionHistory:true});const status=statuses?.value?.[0];if(status?.err)throw new Error(`Solana transaction failed: ${JSON.stringify(status.err)}`);if(status&&(status.confirmationStatus==='confirmed'||status.confirmationStatus==='finalized'))return status;if(++polls%4===0&&lastValidBlockHeight){const height=await connection.getBlockHeight('confirmed');if(height>lastValidBlockHeight)throw new Error(`Solana transaction expired before confirmation. Signature: ${signature}`)}await sleep(900)}throw new Error(`Solana confirmation is taking longer than expected. Signature: ${signature}. Check it before retrying.`)}
async function send(tx){const latest=await connection.getLatestBlockhash('confirmed');tx.feePayer=owner;tx.recentBlockhash=latest.blockhash;let sig;if(provider.signAndSendTransaction){const r=await provider.signAndSendTransaction(tx);sig=typeof r==='string'?r:r?.signature}else{const signed=await provider.signTransaction(tx);sig=await connection.sendRawTransaction(signed.serialize(),{skipPreflight:false,maxRetries:4})}if(!sig)throw new Error('Wallet returned no transaction signature.');await waitForSignatureConfirmation(sig,latest.lastValidBlockHeight);return sig}
async function prepare(){if(!owner)await connect();const treasury=new PublicKey(cfg.prelaunchTreasuryWallet),mint=new PublicKey(cfg.usdcMint),ata=await getAssociatedTokenAddress(mint,treasury);const existing=await connection.getAccountInfo(ata,'confirmed');if(existing){log(`Treasury USDC receiving account ready: ${ata.toBase58()}`);$('preTreasuryStatus').textContent='READY';return}const tx=new Transaction().add(createAssociatedTokenAccountInstruction(owner,ata,treasury,mint));const sig=await send(tx);if(!await connection.getAccountInfo(ata,'confirmed'))throw new Error('USDC receiving account was not created.');$('preTreasuryStatus').textContent='READY';log(`Treasury USDC receiving account created: ${ata.toBase58()} · ${sig}`)}
function install(){if(!/^\/owner(?:\/|$)/.test(location.pathname))return;const shell=document.querySelector('.owner-shell');if(!shell||$('preTreasuryPrep'))return;const section=document.createElement('section');section.className='owner-card';section.id='preTreasuryPrep';section.innerHTML=`<h2>Pre-launch treasury receiving account</h2><p>Prepare the Solana USDC associated token account used by the pre-launch treasury before allocation access opens. This prevents a buyer from paying the treasury account-creation rent during checkout.</p><div class="owner-actions"><button class="btn btn-secondary" id="preTreasuryPrepare">Prepare / verify USDC receiving account</button><span class="state" id="preTreasuryStatus">CHECK</span></div><pre class="launch-log" id="preTreasuryLog" style="min-height:70px">No USDC treasury check yet.</pre>`;const target=$('prelaunchPresaleControl');if(target)target.insertAdjacentElement('afterend',section);else shell.appendChild(section);$('preTreasuryPrepare').onclick=()=>prepare().catch(err=>log(`ERROR: ${err.message}`))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
